# Generated by Django 4.0.1 on 2022-01-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='desc',
        ),
    ]
