# Generated by Django 4.0.1 on 2022-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linkWeb',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
